name: update_index
project_id: prj_h51x37siq3qan75kl4fc5havwn
cluster_env: ray-assistant
compute_config: ray-assistant-g5.8xlarge
runtime_env:
  working_dir: .
entrypoint: bash update-index.sh
max_retries: 0
